Conditions:
  ShouldSetupCustomDomain: !And
    - !Not
      - !Equals
        - ${env:API_DOMAIN_NAME, ''}
        - ''
    - !Not
      - !Equals
        - ${env:ROUTE53_HOSTED_ZONE_ID, ''}
        - ''

Resources:
  APIGWCustomDomainCertificate:
    Condition: ShouldSetupCustomDomain
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: ${env:API_DOMAIN_NAME, ''}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: ${env:API_DOMAIN_NAME, ''}
          HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID, ''}

  APIGWCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: ShouldSetupCustomDomain
    Properties:
      DomainName: ${env:API_DOMAIN_NAME, ''}
      RoutingMode: API_MAPPING_ONLY
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          IpAddressType: ipv4
          SecurityPolicy: TLS_1_2
          CertificateArn: !Ref APIGWCustomDomainCertificate

  APIGWCustomDomainMapping:
    Condition: ShouldSetupCustomDomain
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref HttpApi
      DomainName: !Ref APIGWCustomDomain
      Stage: $default

  APIGWCustomDomainDNSRecord:
    Condition: ShouldSetupCustomDomain
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID, ''}
      Type: A
      Name: !Ref APIGWCustomDomain
      AliasTarget:
        HostedZoneId: !GetAtt APIGWCustomDomain.RegionalHostedZoneId
        DNSName: !GetAtt APIGWCustomDomain.RegionalDomainName
